name: CI-Atenea

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "atenea/**"
      - ".github/workflows/build-atenea.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "atenea/**"
      - ".github/workflows/build-atenea.yml"

jobs:
  build-atenea:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ğŸ³ Start all the environment Mysql
        run: make start-mysql

      - name: ğŸ³ Start all the environment Atenea
        run: |-
          cd atenea
          make start

      - name: Install deps Atenea
        run: |-
          cd atenea
          make deps

      - name: ğŸ”¦ Lint Atenea
        run: |-
          cd atenea
          make cs

      - name: Migrations
        run: |-
          cd atenea
          make migration-force

      - name: Fixtures
        run: |-
          cd atenea
          make fixtures

      - name: âœ… Run the tests
        run: |-
          cd atenea
          make test
      

