name: CI-Auth

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "auth/**"
  pull_request:
    branches: [ master ]
    paths:
      - "auth/**"

jobs:
  build-auth:

    environment: dev

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ğŸ³ Start all the environment Mysql
        run: make start-mysql

      - name: ğŸ³ Start all the environment Auth
        run: |-
          cd auth
          make start

      - name: ğŸ³ Start all the environment Auth
        run: |-
          cd auth
          make view-key

#      - name: ğŸ”¦ Lint Auth
#        run: |-
#          cd auth
#          make cs
#
#      - name: âœ… Run the tests
#        run: |-
#          cd auth
#          make test